config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "tickets#index"
  post '/ticket/guest_sign_in', to: 'tickets#new_guest'
  resources :tickets do
    resources :users
    resources :orders
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  attr_accessor :token
  validates :token, presence: true

  has_one :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :ticket
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  def index
    @tickets = Ticket.all
  end

  def new
    @ticket = Ticket.new
  end

  def create
    # Ticket.create(ticket_params)
    @ticket = Ticket.new(ticket_params)
    if @ticket.valid?
      pay_ticket
      @ticket.save
      return redirect_to root_path
    else
      render 'index'
    end
  end

  # def show
  #   @ticket = Ticket.new
  #   @tickets = @ticket.comments.includes(:user)
  # end

  def new_guest
    user = User.find_or_create_by(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
    sign_in user
    redirect_to root_path
  end


  private

  def ticket_params
    # @ticket = Ticket.find(params[:ticket_id])
    params.permit(:token, :price)
  end

  def pay_ticket
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    Payjp::Charge.create(
      amount: 100,  # 商品の値段
      card: ticket_params[:token],    # カードトークン
      currency: 'jpy'                 # 通貨の種類
    )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @name = current_user.name
    @tickets = current_user.id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnyOne</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  　<header class="header">
    <div class="header__bar row">
      <h1 class="grid-6"><a href="/">AnyOne</a></h1>
      <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <span><%= current_user.name %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/tickets/ticket_id/users/id#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
          <%# <%= link_to "投稿する", new_tweet_path, class: "post" %> 
        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to 'ゲスト', ticket_guest_sign_in_path, method: :post, class: "post" %>
          <%= link_to "ログイン", new_user_session_path, class: "post" %>
          <%= link_to "新規登録", new_user_registration_path, class: "post" %>
        </div>
      <% end %>
    </div>
  </header>
    <%= yield %>
    <footer>
      <p>
        If you can dream it, you can do it.
      </p>
    </footer>
  </body>
</html>

app/views/tickets/index.html.erb
<div class='title-contents'>
<%= video_tag "earth.mov", class: "landing_video", loop: true, autoplay: true, muted: true, width: "100%" %>
    <ul class='possible'>
      <li class='mentor'></li>
        <h1 class='exp'>
          <span class='exp-text'>Make a dream come true</span>
        </h1>
        <a class='exp-description'>
        <span>1人1口$1から抽選に参加できるグローバル宝くじ</span>
        <span><%= image_tag "asia.png", alt: "", id: "assets", class: "lang-image", width: "200px" %></span>
        </a>
      </li>

      <li class='mentor2'></li>
        <h1 class='exp2'>
          <span class='exp2-text'>Strike it rich × contribution</span>
        </h1>
        <a class='exp2-description'>
        <span>収益金の一部は慈善団体に寄付しています</span>
        <span><%= image_tag "money.png", alt: "", id: "assets", class: "lang-image2", width: "200px" %></span>
        </a>
      </li>

      <li class='mentor3'></li>
        <h1 class='exp3'>
          <span class='exp3-text'>Every Friday is your chance</span>
        </h1>
        <a class='exp3-description'>
        <span>毎週金曜日があなたの抽選日です</span>
        <span><%= image_tag "lucky.png", alt: "", id: "assets", class: "lang-image3", width: "200px" %></span>
        </a>
      </li>
<%# 購入機能 %>
      <div class='transaction-contents'>

<%# スロットマシーン %>

<%# スロットマシーン %>
        <div class='transaction-main'>
          <h1 class='transaction-title-text'>
                <a id="btn-custom01-front"></a>
                購入する<br>
            Confirmation of purchase details<br>
            ⬇︎<br>
            ⬇︎<br>
            ⬇︎
          </h1>
      </div>
    
<%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <%= image_tag "asia.png", class: 'buy-item-img' %>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= "1dream" %>
        </h2>
        <div class='buy-item-price'>
          <p class='item-price-sub-text'> $1 </p>
        </div>
      </div>
    </div>
    <%# /購入内容の表示 %>

    <%# 支払額の表示 %>
    <div class='item-payment'>
      <h1 class='item-payment-title'> payment </h1>
      <p class='item-payment-price'>$1</p>
    </div>
    <%# /支払額の表示 %>

    <%= form_with url: tickets_path, id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>
    <%# カード情報の入力 %>
    <%# <%= render 'shared/error_messages', model: @ticket%> 

    <div class='credit-card-form'>
      <h1 class='info-input-haedline'>
        credit card
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-tex">カード情報</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'number', class:"input-default", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
        <div class='available-card'>
          <%= image_tag 'card-visa.gif', class: 'card-logo'%>
          <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
          <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
          <%= image_tag 'card-amex.gif', class: 'card-logo'%>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">有効期限</label>
          <span class="indispensable">必須</span>
        </div>
        <div class='input-expiration-date-wrap'>
          <%= f.text_area 'exp_month', class:"input-expiration-date", id:"card-exp-month", placeholder:"例)3" %>
          <p>月</p>
          <%= f.text_area 'exp_year', class:"input-expiration-date", id:"card-exp-year", placeholder:"例)23" %>
          <p>年</p>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">セキュリティコード</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field "cvc",class:"input-default", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
      </div>
    </div>
    <div class='buy-btn'>
      <%= f.submit "BUY" ,class:"buy-red-btn" %>
    </div>
    <% end %>
  </div>
</div>
<%# 購入機能 %>

   
<%# BUYボタン %>
<div class='purchase-btn'>
  <a href="#btn-custom01-front">BUY</span>
  <i class="fas fa-angle-right fa-position-right"></i>
  </a>
</div>
<%# BUYボタン %>

app/views/users/show.html.erb
<div class="have-ticket">
  <p><%= @name %>さんはチケットを持っています！</p>
  
      <%# <span class="name"><%= ticket.price %>
      <head>
<meta charset="utf-8">
<title>スロットマシーン</title>
<style>
input {
	width:40px;
	font-size:30px;
  text-align:center;
}
button {
	width:40px;
}
.x1 {
	padding:10px 0;
}
.x1 div {
	float:left;
	width:60px;
	text-align:center;
}
</style>
<script>
window.onload = function() {
	var a = document.getElementById('a');
	var b1 = document.getElementById('b1');
	var b2 = document.getElementById('b2');
	var b3 = document.getElementById('b3');
	var c1 = document.getElementById('c1');
	var c2 = document.getElementById('c2');
	var c3 = document.getElementById('c3');
	var t1 = null;
	var t2 = null;
	var t3 = null;

	function start() {
		if (t1) {
			clearInterval(t1);
		}
		if (t2) {
			clearInterval(t2);
		}
		if (t3) {
			clearInterval(t3);
		}
		c1.value = Math.floor(Math.random() * 10);
		c2.value = Math.floor(Math.random() * 10);
		c3.value = Math.floor(Math.random() * 10);
		t1 = setInterval(function () {
			c1.value = (+c1.value + 1) % 10;
		}, 50);
		t2 = setInterval(function () {
			c2.value = (+c2.value + 1) % 10;
		}, 50);
		t3 = setInterval(function () {
			c3.value = (+c3.value + 1) % 10;
		}, 50);
	}

	function stop1() {
		if (t1) {
			clearInterval(t1);
			t1 = null;
		}
		check();
	}

	function stop2() {
		if (t2) {
			clearInterval(t2);
			t2 = null;
		}
		check();
	}

	function stop3() {
		if (t3) {
			clearInterval(t3);
			t3 = null;
		}
		check();
	}

	function check() {
		if (!t1 && !t2 && !t3) {
			if (c1.value == c2.value && c1.value == c3.value) {
				alert('Congratulations！');
			} else {
				alert('はずれ！');
			}
		}
	}

	a.addEventListener('click', start);
	b1.addEventListener('click', stop1);
	b2.addEventListener('click', stop2);
	b3.addEventListener('click', stop3);

	start();
}
</script>
</head>
<body>
	<button type="button" id="a">運試し</button>
	<div class="x1">
		<div>
			<input type="text" id="c1">
			<button type="button" id="b1">stop</button>
		</div>
		<div>
			<input type="text" id="c2">
			<button type="button" id="b2">stop</button>
		</div>
		<div>
			<input type="text" id="c3">
			<button type="button" id="b3">stop</button>
		</div>
	</div>
</body>
</html>
    
</div>